-- =============================================================================
-- AURA — Auth: e-mail + CAPTCHA (leitura obrigatória antes de “Run”)
-- =============================================================================
--
-- O QUE NÃO DÁ PARA FAZER COM SQL NO SUPABASE
-- --------------------------------------------
-- • Ligar/desligar Google OAuth
-- • Colar Client ID / Secret do Google
-- • Redirect URLs (login.html, etc.)
--
-- Isso é só no painel: Project Settings não expõe estas chaves em tabelas
-- públicas que possas alterar com segurança. Usa sempre:
--   Dashboard → Authentication → Providers / URL Configuration
--
-- Para ficares só com E-MAIL + SENHA: no painel, em Providers, desliga Google
-- (e outros OAuth que não queiras). Não precisas de correr SQL para isso.
--
-- CAPTCHA ANTI-ROBÔ (Turnstile ou hCaptcha)
-- -----------------------------------------
-- Também não se “cria” por SQL. Passos no painel Supabase:
--   1) Authentication → Attack Protection (ou Bot / Abuse protection)
--   2) Ativar proteção e escolher Cloudflare Turnstile OU hCaptcha
--   3) Colar o SECRET do fornecedor (Turnstile: secret key; hCaptcha: secret)
--
-- No site (Aura), em supabase-config.js, define a SITE KEY pública:
--   window.AURA_TURNSTILE_SITE_KEY = '...';
--
-- O ficheiro aura-captcha.js envia o token no login e no cadastro.
-- Se deixares a site key vazia, o widget não aparece (CAPTCHA desligado no front).
--
-- =============================================================================
-- Nada abaixo altera a base de dados; podes executar só para marcar como lido.
-- =============================================================================

SELECT 1 AS lido_instrucoes_auth;
